var Elevator = require('../lib/elevator');

//Elevator simulation
// Instantiate with number of elevators and number of floors
module.exports = function (numElevators, numFloors) {
    'use strict';
    var elevators = [],
        i;

    //Handles messages generated by the elevators
    function handleMessage(msg) {
        console.log(msg);
    }

    //Initializes elevator objects
    for (i = 0; i < numElevators; i += 1) {
        elevators.push(new Elevator(i, numFloors, handleMessage));
    }

    //Define function to handle a set of call requests
    this.processCallRequests = function (callsMap) {
        var time = 0,
            calls,
            j;

        //Reset all elevators
        for (i = 0; i < numElevators; i += 1) {
            elevators[i].reset();
        }

        while (true) {
            //Get call for current time
            calls = callsMap[time];

            //Each elevator broadcasts its state to all the other elevators
            for (i = 0; i < numElevators; i += 1) {
                elevators[i].broadcastState(elevators);
            }

            //Send call request
            for (i = 0; i < numElevators; i += 1) {
                for (j = 0; calls && calls.length > 0; j += 1) {
                    //Receive the call requests
                    if ( !elevators[i].receiveMessage({
                        type: 'CALL',
                        startFloor: calls[j].startFloor,
                        endFloor: calls[j].endFloor
                    }) ) {
                        //Handle rejected message
                    };
                }

                //Advance state of elevator
                elevators[i].tick();
            }

            //Advance time counter
            time += 1;
        }
    };
};
